---
title: 'readme'
format: html
jupyter: python3
python:
  path: .venv/bin/python
execute:
  dir: project
---

### Create a project Vitual Environment

(highly recommended, but not required)

` ` ` run in terminal

python3 -m venv .venv

Code chunks must be run in order. If you make changes to inputs in an earlier code chunk rerun all (and review manual overrides as needed) chunks below in order.

` ` ` ` ` `  run in terminal if venv not activated in new session

source .venv/bin/activate

## Install Required Packages

(install scn_redcap_clean in editable mode)

` ` ` {run in terminal}

pip install -e .

` ` ` ` ` `  {run in terminal if the code chunk in your qmd aren't running}

pip install jupyter


` ` ` ` ` `  {for hipaa data: run in terminal to ensure hipaa data is never pushed to git}

git remote set-url --push origin no_push_allowed


# Required Imports, Config and Download

For additional config settings you can also look in config.py

(If you change anything in this chunk, or any config.py variables you must rerun all the
chunks below)


**Raw data & the data dictionary must be in the config.original_data folder before running**
Raw data (config.csv_list) & data dictionary (config.data_dict) config.raw_data_dirs

Update all config. before running


**Download and install from: https://ollama.com/download   .**
(Only required for local ai text extraction in medication and genomics steps)
[If you don't need either step, you can skip clinical instead (see Extra Configs)]


```{python}
#| label: Imports and Config
from scn_redcap_clean import Cleaner, config, days, months, years # local import

# Original Data Folder(s) (files can be in subfolders of these folders too)
config.original_data_folder = ['files_toy']

# Data Dictionary
config.data_dict = 'ToyDict.csv'

# Module Specific
config.modules = ['toy',] # as listed in the Data Dictionary 'Form Name' column

config.csv_list = ['Toy1', 'Toy2.csv']  # raw data csvs for merge

# csv must have all columns of the module(s) you are filtering by (extra modules/cols are fine)
config.raw_module_csv = 'Toy1'

config.med_text_cols = ['toy_meds', 'toy_supps', 'past_meds']

config.c_genomic = 'genomic_text1'
config.p_genomic = 'genomic_p._text2'

config.genomic_cols = [config.c_genomic , config.p_genomic ]

# all columns marked text in the data dictionary you don't want translated
config.no_translate_cols = config.med_text_cols + config.genomic_cols + [
      config.birthdate, config.merge_on_id_column,
      ]

# alternatively you can manually set language_text_columns you want translated (see extras)

config.age_units = [days, months, years]

config.include_age_groups = True 

# ignore 'age_groups' if include_age_groups = False
# age group bins (always starts at 0)
config.age_groups = { # adjust with  (max. age in days/months/years, 'label for ages included in interval')
    days: [
        (7, '0-7 days'),
        (28, '8-28 days'),
        (90, '29-90 days'),
        (180, '3-5 months'),
        (270, '6-8 months'),
        (365, '9-12 months'),
        (float('inf'), '1+ years')],
    months: [
        (1, '0-1 month'),
        (3, '1-3 months'),
        (6, '4-6 months'),
        (9, '7-8 months'),
        (12, '9-11 months'),
        (24, '12-23 months'),
        (36, '24-35 months'),
        (72, '3-5 years'),
        (float('inf'), '5+ years')],
    years: [
        (1, '< 1'),
        (3, '1-2'),
        (5, '3-4'),
        (12, '5-11'),
        (18, '12-17'),
        (25, '18-24'),
        (35, '25-34'),
        (45, '35-44'),
        (55, '45-54'),
        (65, '55-64'),
        (float('inf'), '65+')]
}

config.meds_dict = 'Toy_clinical_taxonomy.csv'

# auto creates project folders next to your .qmd file
cleaner = Cleaner()

```

##### Extra Configs:

*Custom raw data folder(s) location*

If you want your original raw data folder stored separately from this .qmd file this should be the entire folder path (or paths is stored in multiple folders)

config.original_data_folder = ['entire_older_path', 'if_2nd_folder',]  # run before running cleaner = Cleaner()

*Skip certain steps* 
(age will be included in the last run_{step} = True csv if config.age_units is not None
and 'birthdate' and 'submission date' columns exist and are set in config)
config.run_translation = False
config.run_duplicates = False
config.run_clinical = False



*Manually setting text columns for translation*
List all langauge-dependent text columns (exclude genomic text, etc.) for translation
e.g.
config.language_text_columns = [
  'toy_text1', 'toy_text2', 'toy_text3', 'toy_text4', 'toy_text5']


By default filter_columns = 'birthdate' for creating the duplicate review csv but you
should be able to use more than 1 column;
avoid any open text responses for filters due to typos

e.g.
config.filter_columns = ['birthdate', 'country']


` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `

# cleaner.clean()
Outputs csvs to the 'steps' folder, {step}_manual_override for review and
edits in the 'review' folder, and a .txt for logging any manual override
explanations to the overrides folder.

The data dictionary is used as a map to automatically get all 'Field Type' = 'text' for
translation.

Archive also stores read only copies which will be used for auto summaries.
Rerunning the same stage with different inputs will overwrite files in the 'steps' folder.
Version history csv files are stored in the 'archive' folder for every run with different
back to back input if the contents for the main step file is changed.
(e.g. 2 runs in a row without *any* changes will not create new archive files)

See Extra for manually setting specific columns you do want translated instead.

```{python}
#| label: clean

# if specific terms need overrides after translation add them here & rerun this chunk
config.translation_dict = { 
            '布洛芬':'Ibuprofen',
            'SCN8A':'SCN8A',
           }


cleaner.clean()
```

Other Info:
- Any exact duplicate columns in more than one original raw csv will only be included once.
- A suffix '_{filename}' will be added to identical column names containing at least one
different input for a given participant id.
- config.translation_dict input:
non-english must be the key and the translation (or medical term) the value

##### Extra Config (translation_script_threshold):

If translations are failing involving non-latin scripts adjust config.translation_script_threshold
(detects non-latin characters and assigns language after 3 characters match a specific char. script)
run anywhere before cleaner.clean() 

e.g.
config.translation_script_threshold = 4    # if you don't have many language_text_columns this should be 1 or 2

` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `

# If clean() outputs a translations_for_review

## cleaner.proceed.translated() Replaces non-english with english translations and continues cleaning

After outputing translations, manually review and edit translations_manual_override.csv
in the review folder as needed. The final column in translations_manual_override should be
used to record reasons you made any adjustments to a row.
**Once manual edits are complete move translations_manual_override to the overrides folder.**

Keep the final version of this file without altering filename or column names in the
manual_overrides folder *before running* cleaner.proceed.translated()

The .txt file in the overrides folder is for recording general and brief override
explanations and row deletion (e.g. 'Deleted false positives, language was already english.')
Keep this file in the overrides folder (the summary will eventually archive it).

```{python}
#| label: proceed from translated override
cleaner.proceed.translated()
```

##### Extra cleaner.proceed.translated():
If you want to proceed without inputing any translations instead:

cleaner.proceed.translated(skip_input = True)


` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `


# if clean() or proceed() outputs a duplicates_for_review

## cleaner.proceed.duplicates() removes duplicate submissions based on 'birthdate'

Again, manually review and edit duplicates_manual_override.csv as needed, leaving
explanations in the overrides column of the manual_overrides file and general comments
in the txt.


*For manual overrides Participant_id should be written as {last Participant_id per bday}.999*
Example:
participant_id's for birthdate 1/2/02 are 3, 5, 8
If a manual override is needed the override should be 8.999

(.888 works too, just choose an integer that stands out for you.) If no manual override
(last submission is best) these rows do not need to be included in the manual override,
but it should still work if they are. Add the final version without altering column
names to the overrides folder.

If **all** duplicates do not need a *manual* override, you do not need to move the
duplicate overrides file to the overrides folder, just run the code chunk below to
remove earlier submission duplicates.

Duplicates are identified based on birthdate. (Confirm they are actual duplicates and
not just **shared** birthdates.)

**keep 'flag_shared_birthdate' column empty, unless 2 different people share a birthdate**

See 'Shared Birthdates' below for instructions if needed.

**Once manual edits are complete move this file to the overrides folder.**


[If cleaning config.med_text_cols or config.genomic_cols, expect 
cleaner.proceed.duplicates() to take time.]

```{python}
#| label: proceed from duplicates override
cleaner.proceed.duplicates()

```

##### Extra cleaner.proceed.translated():
If you want to proceed with all duplicates instead:

cleaner.proceed.duplicates(keep_all = True)

all duplicates will remain unchanged (no override occurs)


` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `

##### Shared Birthdates
If any duplicates are clearly different people, the manual override must mark the 
flag_shared_birthdate column for the early submission. If the birthdates are not shared 
this must remain empty.

Flagging a row makes that specific row stay in the final dataset no mater what.

*e.g.*   all rows will be kept
id 1       bday 1/2/10       flag X

id 3       bday 1/2/10       flag X

id 4       bday 1/2/10       flag X


*e.g.*   the id 1 and id 4 will kept
id 1       bday 1/2/10       flag X

id 3       bday 1/2/10       flag

id 4       bday 1/2/10       flag


*e.g.*  id 3 and id 4 will kept
id 1       bday 1/2/10       flag

id 3       bday 1/2/10       flag

id 4       bday 1/2/10       flag X





### if clean() or proceed() outputs a medications_for_review and/or genomics_for_review

## cleaner.proceed.clinical() inputs binary and categorized meds and genomics


Medications and Supplements are extracted using local AI and reported with lowest AI 
confidence scores at the top fo the medications_manual_override.csv (saved to review).

Each AI recommended term is listed in the 'recommended_text' next to the full 'raw_text'
entry. 

Again, manually review and edit medications_manual_override.csv as needed, leaving
explanations in the overrides column of the manual_overrides file and general comments
in the txt.

Change the 'recommended_term' as needed (along with the 'from_column' if it was submitted
in the wrong column e.g. a supplement in seizure medication) 

The 'add_to_ref' column tracks 'MISSING IN REF' medicatons and supplements. 
If the 'recommended_term' is an alias add it to the alias column of the 'meds_dict.csv'
**in the 'ref' folder.**.
If it's a new medication or supplement, insert a new row with the 'functional_class' 
(if applicable), 'Generic Name', and any aliases/abbr. 
(All other columns are optional for your reference, and not included in the code.)

**Once manual edits are complete move 'medications_manual_override' to overrides folder.**
The meds_dict.csv **in the 'ref' folder.** should be updated based on the 'add_to_ref' 
column in 'medications_manual_override.csv' **before running this step.**
'from_column' name's will be classified as medications if 'med' is part of the 
'from_column' name. Edit as needed in 'medications_manual_override.csv' 


### if clean() or proceed()  outputs a medications_for_review and/or genomics_for_review
Add comments to the medications_manual_overrides.txt and genomics_manual_overrides.txt as needed.
```{python}
#| label: proceed from clinical overrides
cleaner.proceed.clinical()

```





##### Extra option Cleaner:
If you've already run and moved overrides to the overrides folder, but still want a new 
review csv, you can either the change use_existing_overrides settings 
when creating cleaner or at any point in the cleaning process.

Initiate with:
cleaner = Cleaner(use_existing_overrides = False)

*or to change in the middle of cleaning*
cleaner.proceed.use_existing_overrides = False


` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` `





# Steps folder csvs 
(if all steps are needed; numbers will adjust if a step is skipped)

### 1_assembled

Merged csvs from csv_list filtered by 'config.module' and 'config.raw_module_csv'.
Only includes participant_id's with at least 1 response in the specified 'config.module'.

### 2_translations

Replaces non-english with english translations if 'translations_manual_override.csv' is 
in the overrides folder

### 3_duplicates

If 'duplicates_manual_override' is not in overrides folder, contains only the last 
submission from the previous step file (usually '2_translations.csv'). 
(Duplicate detection is based on 'config.filter_columns' with default birthdate.) 

If 'duplicates_manual_override.csv' is in the overrides folder, contains the last 
submission based on 'duplicates_manual_override.csv'. Also keeps any rows where the 
'flag_shared' column is not empty


### 4_clinical

Medications/supplements are input as dummy (binary) variables by individual med/sup and 
by the 'functional_class' specified in 'meds_dict.csv' in the 'ref' folder.

Splits protein variants into mutliple columns including both 1 letter and 3 letter amino
acid codes, and a column with the mutation region based on UniProt regions (see 'ref' folder).

Includes approximate age based on each modules 'submission_date' and 'birthdate' 
(or year and month of death)s. Columns included are based on 'config.age_units'



        to be continued...

```
